# Generated by Django 5.1.4 on 2025-02-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
